deployment:
  replicas: 1
  image: 837206354502.dkr.ecr.us-east-1.amazonaws.com/localhelp-frontend
  imageVersion: IMAGE_VERSION

targetGroup:
  arn: arn:aws:elasticloadbalancing:us-east-1:837206354502:targetgroup/localhelp-dev-frontend/055f464eee4f124e